### ISSUE TITLE
left to do

### ISSUE THREAD

**Issue by chesyrin** [chesyrin/12U-summative#7]
- [ ] make prettier
- [x] instructions screen + edit menu to have a button that goes to instructions
- [ ] comment, javadoc IN PROGRESS
- [x] sorting
- [ ] abstract IN PROGRESS
- [x] encapsulation DONE
- [x] error check

**Comment by chesyrin** [comment]
-item extends object for abstract

**Comment by Aaaaaaa3** [comment]
- sort items alphabetically(?) when reading in text file

**Comment by Aaaaaaa3** [comment]
- error check - if the player has not yet collected an item, they cannot submit that number as an answer in the puzzle

**Comment by Aaaaaaa3** [comment]
- [ ] add a note somewhere crediting the images

**Comment by Aaaaaaa3** [comment]
- [ ] try and get rid of warnings
